### ISSUE TITLE
QSPI init should run at reset-init not reset-end

### ISSUE THREAD

**Issue by ali1234** [AndrewCapon/32BlitMacOpenOCD#1]
https://github.com/AndrewCapon/32BlitMacOpenOCD/blob/d9e3b4e52e84b2dd434cc10ea03c16b3d884d1c6/32blitdap.cfg#L212

The problem: if you do a `reset run` then firmware cannot access QSPI. It works if you do `reset init; resume`.

Adding a delay to the firmware to make `qspi_init()` run later fixed the issue, but that is just a work-around.

I think what is happening is that because the event fires on `reset-end` the CPU is unhalted when the init function runs. Then openocd and the firmware both try to write QSPI registers at the same time. That trashes the config and the QSPI stops working entirely.

The openocd docs say this about `reset-init`:

> This is where you would configure PLLs and clocking, set up DRAM so you can download programs that don’t fit in on-chip SRAM, set up pin multiplexing, and so on. (You may be able to switch to a fast JTAG clock rate here, after the target clocks are fully set up.) 

This seems like a more appropriate place for the QSPI init to run, and changing the hook fixes the problem.

**Comment by AndrewCapon** [comment]
Good catch.

I looked at https://github.com/sysprogs/openocd/blob/master/tcl/target/stm32h7x_dual_core.cfg which is what I used as a base and you are quite correct they do it on reset-end, looks like I arsed up!

**Comment by ali1234** [comment]
This is what openocd dev has to say about it:

> (11:42:22) PaulFertser: ali1234: some targets use reset-end for disabling watchdog
> (11:42:27) PaulFertser: ali1234: because it makes sense for debugging
> (11:42:37) PaulFertser: alan_o: initialising flash controller centainly doesn't belong there.
> (11:42:41) PaulFertser: ali1234: ^^
> (11:58:47) PaulFertser: ali1234: reset-init handler is usually used to initialise flash/RAM/etc, whatever is needed for flashing the device, and it's called only during "reset init", not even during "reset halt".
> (11:59:17) PaulFertser: ali1234: so "program" script uses "reset init" automatically prior to trying to write to flash.
> (12:04:42) ali1234: so now i understand why you said "it initializes itself"
> (12:05:27) ali1234: because "reset-end" is always run, even when we are not programming - and we only want openocd to init the chip when programming, otherwise the app code should do it
> (12:05:45) ali1234: ie it should do it itself in that case
> (12:16:15) PaulFertser: ali1234: yes, that's what I meant. Code like that belong to reset-init handler and programming procedure should involve "reset init" command somehow. E.g. default handlers for GDB events includes that prior to erasing the flash.

**Comment by AndrewCapon** [comment]
Fine, you can go with your version.

I will stick with the STM version for this build as it all works fine.

**Comment by ali1234** [comment]
Reported to sysprogs repo: https://github.com/sysprogs/openocd/issues/5

**Comment by AndrewCapon** [comment]
What does that mean?

**Comment by ali1234** [comment]
It means I reported the problem to the repository that you cited as the reason why you don't want to fix it, so that they will fix it for you.

**Comment by ali1234** [comment]
I also added a note to the upstream patch set review: http://openocd.zylin.com/#/c/4321/7
